# docker-compose.yml

# Add this top-level entry




# Use postgres/example user/password credentials
version: '3.1'

services:

#  redis:
#    image: "redis:alpine"
#
#  db:
#    image: postgres
#    restart: always
##    environment:
##      POSTGRES_PASSWORD: example

  web:
    # replace username/repo:tag with your name and image details
    image: mihai1voicescu/wdm:basic
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000"
    networks:
      - webnet

#  app:
#    build: ./
#      ports:
#        - 3000:3000
#      environment:
#        - NODE_ENV=development
#        - PORT=8000
#
#    links:
#      - redis
#    environment:
#      - REDIS_URL=redis://cache
#      # rest of the environment definitions

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080



